spring:
  application:
    name: calbak
  datasource:
    url: jdbc:postgresql://localhost:5432/calbak_db
    username: calbak_user
    password: calbak_password
    driver-class-name: org.postgresql.Driver